(cl:defpackage mybot_pkg-srv
  (:use )
  (:export
   "COMPUTECIRCLEAREA"
   "<COMPUTECIRCLEAREA-REQUEST>"
   "COMPUTECIRCLEAREA-REQUEST"
   "<COMPUTECIRCLEAREA-RESPONSE>"
   "COMPUTECIRCLEAREA-RESPONSE"
  ))

