<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_core">

    <!--<xacro:include filename="inertial_macros.xacro"/>-->
    
    <!--COLORS-->
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="green">
        <color rgba="0.2 1 0.2 1"/>
    </material>

    <material name="red">
        <color rgba="1 0.2 0.2 1"/>
    </material>

    <!--DESIGN-->
    <xacro:property name="chassis_x" value="0.4"/>
    <xacro:property name="chassis_y" value="0.4"/>
    <xacro:property name="chassis_z" value="0.15"/>
    <xacro:property name="wheel_radius" value="0.08"/>
    <xacro:property name="wheel_length" value="0.04"/>
    <xacro:property name="caster_wheel_front_x_origin" value="0.33"/>
    <xacro:property name="caster_wheel_back_x_origin" value="0.07"/>
    <xacro:property name="caster_wheel_radius" value="0.08"/>
    <xacro:property name="chassis_mass" value="0.5"/>
    <xacro:property name="wheel_mass" value="0.1"/>
    
    <!--base-->
    <link name="base_link"></link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.2 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <link name="chassis">
        <visual>
            <geometry>
                <box size="${chassis_x} ${chassis_y} ${chassis_z}" />
            </geometry>
            <material name="LightGrey"/>
            <origin xyz="${chassis_x/2} 0.0 ${chassis_z/2}" rpy="0.0 0.0 0.0"/> 
        </visual>
        <collision> 
            <geometry>
                <box size="${chassis_x} ${chassis_y} ${chassis_z}" />
            </geometry>
        </collision>    
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_x/2}" y="${chassis_y}" z="${chassis_z}">
            <origin xyz="${chassis_x/2} 0.0 ${chassis_z/2}" rpy="0.0 0.0 0.0"/> 
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <!--left wheel-->
    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0.0 0.222 0.0" rpy="${-pi/2} 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="red"/>    
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0.0 0.222 0.0" rpy="${-pi/2} 0.0 0.0"/> 
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

     <!--right wheel-->
    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0.0 -0.222 0.0" rpy="${pi/2} 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <axis xyz="0.0 0.0 -1.0"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="red"/>    
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0.0 -0.222 0.0" rpy="${pi/2} 0.0 0.0"/> 
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    
    <!--caster wheel front-->
    <joint name="caster_wheel_front_joint" type="fixed">
        <origin xyz="${caster_wheel_front_x_origin} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="chassis"/>
        <child link="caster_wheel_front_link"/>
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    </joint>

    <link name="caster_wheel_front_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="${caster_wheel_front_x_origin} 0.0 0.0" rpy="0.0 0.0 0.0"/> 
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_front_link">
        <material>Gazebo/Grey</material>
        <mu1 value="0.0"/>
        <mu2 value="0.0"/>
    </gazebo>

    <!--caster wheel back-->
    
    <joint name="caster_wheel_back_joint" type="fixed">
        <origin xyz="${caster_wheel_back_x_origin} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="chassis"/>
        <child link="caster_wheel_back_link"/>
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    </joint>

    <link name="caster_wheel_back_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="${caster_wheel_back_x_origin} 0.0 0.0" rpy="0.0 0.0 0.0"/> 
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_back_link">
        <material>Gazebo/Grey</material>
        <mu1 value="0.0"/>
        <mu2 value="0.0"/>
    </gazebo>    

</robot>