// Generated by gencpp from file mybot_pkg/ComputeCircleArea.msg
// DO NOT EDIT!


#ifndef MYBOT_PKG_MESSAGE_COMPUTECIRCLEAREA_H
#define MYBOT_PKG_MESSAGE_COMPUTECIRCLEAREA_H

#include <ros/service_traits.h>


#include <mybot_pkg/ComputeCircleAreaRequest.h>
#include <mybot_pkg/ComputeCircleAreaResponse.h>


namespace mybot_pkg
{

struct ComputeCircleArea
{

typedef ComputeCircleAreaRequest Request;
typedef ComputeCircleAreaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeCircleArea
} // namespace mybot_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mybot_pkg::ComputeCircleArea > {
  static const char* value()
  {
    return "c314357897f85c5c2498418b07dbcead";
  }

  static const char* value(const ::mybot_pkg::ComputeCircleArea&) { return value(); }
};

template<>
struct DataType< ::mybot_pkg::ComputeCircleArea > {
  static const char* value()
  {
    return "mybot_pkg/ComputeCircleArea";
  }

  static const char* value(const ::mybot_pkg::ComputeCircleArea&) { return value(); }
};


// service_traits::MD5Sum< ::mybot_pkg::ComputeCircleAreaRequest> should match
// service_traits::MD5Sum< ::mybot_pkg::ComputeCircleArea >
template<>
struct MD5Sum< ::mybot_pkg::ComputeCircleAreaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mybot_pkg::ComputeCircleArea >::value();
  }
  static const char* value(const ::mybot_pkg::ComputeCircleAreaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mybot_pkg::ComputeCircleAreaRequest> should match
// service_traits::DataType< ::mybot_pkg::ComputeCircleArea >
template<>
struct DataType< ::mybot_pkg::ComputeCircleAreaRequest>
{
  static const char* value()
  {
    return DataType< ::mybot_pkg::ComputeCircleArea >::value();
  }
  static const char* value(const ::mybot_pkg::ComputeCircleAreaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mybot_pkg::ComputeCircleAreaResponse> should match
// service_traits::MD5Sum< ::mybot_pkg::ComputeCircleArea >
template<>
struct MD5Sum< ::mybot_pkg::ComputeCircleAreaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mybot_pkg::ComputeCircleArea >::value();
  }
  static const char* value(const ::mybot_pkg::ComputeCircleAreaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mybot_pkg::ComputeCircleAreaResponse> should match
// service_traits::DataType< ::mybot_pkg::ComputeCircleArea >
template<>
struct DataType< ::mybot_pkg::ComputeCircleAreaResponse>
{
  static const char* value()
  {
    return DataType< ::mybot_pkg::ComputeCircleArea >::value();
  }
  static const char* value(const ::mybot_pkg::ComputeCircleAreaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYBOT_PKG_MESSAGE_COMPUTECIRCLEAREA_H
