// Generated by gencpp from file mybot_pkg/ComputeCircleAreaResponse.msg
// DO NOT EDIT!


#ifndef MYBOT_PKG_MESSAGE_COMPUTECIRCLEAREARESPONSE_H
#define MYBOT_PKG_MESSAGE_COMPUTECIRCLEAREARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mybot_pkg
{
template <class ContainerAllocator>
struct ComputeCircleAreaResponse_
{
  typedef ComputeCircleAreaResponse_<ContainerAllocator> Type;

  ComputeCircleAreaResponse_()
    : area(0.0)  {
    }
  ComputeCircleAreaResponse_(const ContainerAllocator& _alloc)
    : area(0.0)  {
  (void)_alloc;
    }



   typedef double _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeCircleAreaResponse_

typedef ::mybot_pkg::ComputeCircleAreaResponse_<std::allocator<void> > ComputeCircleAreaResponse;

typedef boost::shared_ptr< ::mybot_pkg::ComputeCircleAreaResponse > ComputeCircleAreaResponsePtr;
typedef boost::shared_ptr< ::mybot_pkg::ComputeCircleAreaResponse const> ComputeCircleAreaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator1> & lhs, const ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator1> & lhs, const ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mybot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "502b7bd5115b3b4f57d03446f9208d12";
  }

  static const char* value(const ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x502b7bd5115b3b4fULL;
  static const uint64_t static_value2 = 0x57d03446f9208d12ULL;
};

template<class ContainerAllocator>
struct DataType< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mybot_pkg/ComputeCircleAreaResponse";
  }

  static const char* value(const ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 area\n"
;
  }

  static const char* value(const ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeCircleAreaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mybot_pkg::ComputeCircleAreaResponse_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    Printer<double>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYBOT_PKG_MESSAGE_COMPUTECIRCLEAREARESPONSE_H
