// Generated by gencpp from file mybot_pkg/ComputeCircleAreaRequest.msg
// DO NOT EDIT!


#ifndef MYBOT_PKG_MESSAGE_COMPUTECIRCLEAREAREQUEST_H
#define MYBOT_PKG_MESSAGE_COMPUTECIRCLEAREAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mybot_pkg
{
template <class ContainerAllocator>
struct ComputeCircleAreaRequest_
{
  typedef ComputeCircleAreaRequest_<ContainerAllocator> Type;

  ComputeCircleAreaRequest_()
    : radius(0.0)  {
    }
  ComputeCircleAreaRequest_(const ContainerAllocator& _alloc)
    : radius(0.0)  {
  (void)_alloc;
    }



   typedef double _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeCircleAreaRequest_

typedef ::mybot_pkg::ComputeCircleAreaRequest_<std::allocator<void> > ComputeCircleAreaRequest;

typedef boost::shared_ptr< ::mybot_pkg::ComputeCircleAreaRequest > ComputeCircleAreaRequestPtr;
typedef boost::shared_ptr< ::mybot_pkg::ComputeCircleAreaRequest const> ComputeCircleAreaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator1> & lhs, const ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator1> & lhs, const ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mybot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34d1b51a3aa2a07a0194bc3c5de27677";
  }

  static const char* value(const ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34d1b51a3aa2a07aULL;
  static const uint64_t static_value2 = 0x0194bc3c5de27677ULL;
};

template<class ContainerAllocator>
struct DataType< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mybot_pkg/ComputeCircleAreaRequest";
  }

  static const char* value(const ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 radius\n"
"\n"
;
  }

  static const char* value(const ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeCircleAreaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mybot_pkg::ComputeCircleAreaRequest_<ContainerAllocator>& v)
  {
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYBOT_PKG_MESSAGE_COMPUTECIRCLEAREAREQUEST_H
